server:
  port: 30009
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/netproxy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


app:
  port: 30010
